### ISSUE TITLE
modify properties after creation

### ISSUE THREAD

**Issue by Jens-G** [cosh/fallen-8#27]
I just noticed that I can modify properties via the REST service interface, at least it is part of the contract. 

But when I link directly against the assembly, I can't do that, because ```TryAddProperty()``` (which should be named ```TryAddOrUpdateProperty()```) and ```TryRemoveProperty()``` both are ```internal```, not ```public```, hence not accessible from the outside. 

Is there a reason for that which I overlook, or is it just inconsistent and they could safely be set to ```public``` without running into trouble?

**Comment by Jens-G** [comment]
Hi,
is this project maintained actively or is it just dead?

**Comment by cosh** [comment]
Hi Jens,

it's not dead :).

Cheers, Henning.

**Comment by cosh** [comment]
I saw that you fixed some NPE. pull request?
