### ISSUE TITLE
FinishRead/WriteResource() not called in case of an exception

### ISSUE THREAD

**Issue by Jens-G** [cosh/fallen-8#28]
The matching calls to FinishRead/WriteResource() are not called when an exception occurs while holding the lock. This essentially deadlocks the whole application.

**Comment by cosh** [comment]
k, pls fork (check), fix (check) and create a pull request :).

Thx!!!!

**Comment by Jens-G** [comment]
I don't understand this. I just don't. Maybe you should disable the abilöity to report issues, because the onlys thing it does its wasting the reporters time.

**Comment by cosh** [comment]
Be more specific next time. Guidance can be found here: https://www.google.de/webhp?#safe=off&q=how+to+report+a+bug

**Comment by Jens-G** [comment]
I assumed you know your own code. But, oky, let#s be more specific: The matching calls to FinishRead/WriteResource() are not called when an exception occurs while holding the lock. This essentially deadlocks the whole application. All affected code location follow this pattern:

```
			if (ReadResource()) 
			{
				// do some stuff that may fail
				FinishReadResource();   // not callen when an exception occurs
				return someResult;
			}
        }
```
There are way too many places to list them all here.
