### ISSUE TITLE
Synchronization issues

### ISSUE THREAD

**Issue by Jens-G** [cosh/fallen-8#30]
The synchronization concept seems largely broken when it comes to operations requiring more than one step executed atomically. Because all synchronisation happens inside the methods, there is no way to ensure that a sequence like (pseudo code)

      var elms = graph.FindSetOfElements()
      graph.Delete(elms)

is executed atomically. The above scenario becomes a problem, when some other thread tries to manipulate or even read some of these elements at the same time.

The (bad) workaround is to add some R/W lock to the whole thing and use that as a sync mechanism instead of reyling on the builtin locks.

**Comment by cosh** [comment]
It's not broken... It's just not done. A real 2pc would be nice incl TIDs, rollback and all the other goodies would be desirable. 
I would be glad if you could help me regarding a complete transactional database implementation.

**Comment by Jens-G** [comment]
So it stays this way: Pretending to be thread safe while in reality it isn't. Good to know.

**Comment by cosh** [comment]
For bigger change requests a dedicated issue needs to be created. This issue has been closed because it works as designed.
