### ISSUE TITLE
OOM during Save()

### ISSUE THREAD

**Issue by Jens-G** [cosh/fallen-8#31]
I reproduceably get a OOM crash when I reach a certain level of data in the database. It is always at the same place in the code, while attempting to Save() the data:

	System.OutOfMemoryException wurde nicht von Benutzercode behandelt.
	  HResult=-2147024882
	  Message=Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
	  Source=mscorlib
	  StackTrace:
		   bei System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
		   bei System.IO.BinaryWriter.Write(Int32 value)
		   bei Framework.Serialization.SerializationWriter..ctor(Stream stream, Boolean allowUpdateHeader) in d:\DEVELOP\MyProject\3rdparty\fallen-8\Dependencies\FastSerializer\Serialization\SerializationWriter.cs:Zeile 208.
		   bei Framework.Serialization.SerializationWriter..ctor(Stream stream) in d:\DEVELOP\MyProject\3rdparty\fallen-8\Dependencies\FastSerializer\Serialization\SerializationWriter.cs:Zeile 186.
		   bei NoSQL.GraphDB.Persistency.PersistencyFactory.SaveIndex(String indexName, IIndex index, String path) in d:\DEVELOP\MyProject\3rdparty\fallen-8\Fallen-8\Persistency\PersistencyFactory.cs:Zeile 277.
		   bei NoSQL.GraphDB.Persistency.PersistencyFactory.<>c__DisplayClass7.<Save>b__1() in d:\DEVELOP\MyProject\3rdparty\fallen-8\Fallen-8\Persistency\PersistencyFactory.cs:Zeile 199.
		   bei System.Threading.Tasks.Task`1.InnerInvoke()
		   bei System.Threading.Tasks.Task.Execute()

Environment is 64bit Windows 8.1 with lots of free RAM, if that matters.

**Comment by cosh** [comment]
Thx for testing. So you compiled everything for 64bit? how many nodes/edges?

**Comment by Jens-G** [comment]
> So you compiled everything for 64bit? 

I used the original Setup of the projects, whatever that is. The machine's OS is 64 bit.

> how many nodes/edges?

Somewhere in the range of 500.000, don't have the exact number yet.

**Comment by cosh** [comment]
not reproducible...
